/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./components/AppBar.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Quiz: typeof import('./components/Quiz.vue')['default']
    Quiz1: typeof import('./components/Quiz1.vue')['default']
    Quiz2: typeof import('./components/Quiz2.vue')['default']
    QuizStatus: typeof import('./components/QuizStatus.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Setup: typeof import('./components/Setup.vue')['default']
  }
}
